### ISSUE TITLE
Not able to forge compile

### ISSUE THREAD

**Issue by pabl0ramirez** [Cyfrin/foundry-simple-storage-f23#15]
Added Solc 0.8.19 in foundry.toml file and it removed  **Failed to install Solc 0.8.19: error sending request for url (https://binaries.soliditylang.org/linux-amd64/list.json)**. Issue persists.

cojo@HPE-5CG043492T:~/foundry/foundry-simple-storeage$ forge compile
[⠊] Compiling...
[⠒] Compiling 1 files with Solc 0.8.19
[⠔] Installing Solc version 0.8.19
[⠒] **Failed to install Solc 0.8.19: error sending request for url (https://binaries.soliditylang.org/linux-amd64/list.json)**
Error: 
error sending request for url (https://binaries.soliditylang.org/linux-amd64/lis**t.json)**

Context:
- Error #0: client error (Connect)
- Error #1: invalid peer certificate: UnknownIssuer

**Comment by cromewar** [comment]
Hello @pabl0ramirez 

I assume you are using WSL. It seems that the problem is that it's trying to connect to the Solidity Repos without success.
This might be a WSL connection error. 

Can you open the Powershell/Windows terminal and run `wsl --shutdown,` open the WSL instance again, then give it another try?

Also, for context, can you share the `.toml` file?

**Comment by pabl0ramirez** [comment]
Good day Vasiliy, 

Thanks for responding back. Seems that my jobs FW is the cause. I was just able to run 'Forge Build' from my home PC without the error. 

Thanks again!!

Pablo Ramirez
